//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace Tecnostore.tDadosCartao {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="CardBinding", Namespace="urn:Card")]
    public partial class Card : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback ValidarCartaoOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public Card() {
            this.Url = global::Tecnostore.Properties.Settings.Default.Tecnostore_tDadosCartao_Card;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event ValidarCartaoCompletedEventHandler ValidarCartaoCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("urn:Card#ValidarCartao", RequestNamespace="urn:Card", ResponseNamespace="urn:Card")]
        [return: System.Xml.Serialization.SoapElementAttribute("msg")]
        public string ValidarCartao(tDadosCartao dadosCartao) {
            object[] results = this.Invoke("ValidarCartao", new object[] {
                        dadosCartao});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void ValidarCartaoAsync(tDadosCartao dadosCartao) {
            this.ValidarCartaoAsync(dadosCartao, null);
        }
        
        /// <remarks/>
        public void ValidarCartaoAsync(tDadosCartao dadosCartao, object userState) {
            if ((this.ValidarCartaoOperationCompleted == null)) {
                this.ValidarCartaoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnValidarCartaoOperationCompleted);
            }
            this.InvokeAsync("ValidarCartao", new object[] {
                        dadosCartao}, this.ValidarCartaoOperationCompleted, userState);
        }
        
        private void OnValidarCartaoOperationCompleted(object arg) {
            if ((this.ValidarCartaoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ValidarCartaoCompleted(this, new ValidarCartaoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="urn:Card")]
    public partial class tDadosCartao {
        
        private string numeroCartaoField;
        
        private int codigoField;
        
        private string nomeClienteField;
        
        private string validadeField;
        
        private double valorField;
        
        private int parcelasField;
        
        private string nomeEmpresaField;
        
        private int cNPJEmpresaField;
        
        /// <remarks/>
        public string NumeroCartao {
            get {
                return this.numeroCartaoField;
            }
            set {
                this.numeroCartaoField = value;
            }
        }
        
        /// <remarks/>
        public int Codigo {
            get {
                return this.codigoField;
            }
            set {
                this.codigoField = value;
            }
        }
        
        /// <remarks/>
        public string NomeCliente {
            get {
                return this.nomeClienteField;
            }
            set {
                this.nomeClienteField = value;
            }
        }
        
        /// <remarks/>
        public string Validade {
            get {
                return this.validadeField;
            }
            set {
                this.validadeField = value;
            }
        }
        
        /// <remarks/>
        public double Valor {
            get {
                return this.valorField;
            }
            set {
                this.valorField = value;
            }
        }
        
        /// <remarks/>
        public int Parcelas {
            get {
                return this.parcelasField;
            }
            set {
                this.parcelasField = value;
            }
        }
        
        /// <remarks/>
        public string NomeEmpresa {
            get {
                return this.nomeEmpresaField;
            }
            set {
                this.nomeEmpresaField = value;
            }
        }
        
        /// <remarks/>
        public int CNPJEmpresa {
            get {
                return this.cNPJEmpresaField;
            }
            set {
                this.cNPJEmpresaField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    public delegate void ValidarCartaoCompletedEventHandler(object sender, ValidarCartaoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ValidarCartaoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ValidarCartaoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591